### ISSUE TITLE
Sample App Cloning Issue

### ISSUE THREAD

**Issue by bfalah** [NorhanKhaled/SkillsAcademy-CAD#24]
Hi,
I tried to clone the sample app by running the following command as indicated in the lecture of unit 3
git clone https://github.com/IBM-Cloud/get-started-node
But I got the following error message:
fatal: could not create work tree dir 'get-started-node': Permission denied

Any help is much appreciated

**Comment by kareem-zakaria** [comment]
Are you running **cmd** as administrator?

**Comment by bfalah** [comment]
Yes I am

Bouchaib Falah, Ph.D
Associate Professor of Software Engineering
School of Science and Engineering
Al Akhawayn University, Ifrane, Morocco
Work: +212535862194
Cell:+212658595282
Fax: +212535862030

________________________________

**Comment by kareem-zakaria** [comment]
I believe the problem is that your current directory that you are trying to clone the app into does not have write/create permissions.

The solution is either creating a different directory where you have ownership (write permissions), or give rights to your current directory.

Kindly refer to this link: https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

I hope this helps.

**Comment by bfalah** [comment]
Yes. I figured out the problem. It is working now.
Thank you

**Comment by kareem-zakaria** [comment]
You're welcome!
